/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Command: typeof import('./src/components/Command.vue')['default']
    Docdata: typeof import('./src/components/Docdata.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCol: typeof import('@layui/layui-vue')['LayCol']
    LayConfigProvider: typeof import('@layui/layui-vue')['LayConfigProvider']
    LayContainer: typeof import('@layui/layui-vue')['LayContainer']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LayRow: typeof import('@layui/layui-vue')['LayRow']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySplitPanel: typeof import('@layui/layui-vue')['LaySplitPanel']
    LaySplitPanelItem: typeof import('@layui/layui-vue')['LaySplitPanelItem']
    LayTab: typeof import('@layui/layui-vue')['LayTab']
    LayTabItem: typeof import('@layui/layui-vue')['LayTabItem']
    LayTextarea: typeof import('@layui/layui-vue')['LayTextarea']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
